import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" >
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <nav style={{ padding: '1rem', background: '#f4f4f4', display: 'flex', justifyContent: 'space-between' }}>
          <div>
            <h1>Weather App</h1>
          </div>
          <div>
            <Link href="/" style={{ margin: '0 1rem' }}>Home</Link>
            <Link href="/about" style={{ margin: '0 1rem' }}>About</Link>
            <Link href="/contact" style={{ margin: '0 1rem' }}>Contact</Link>
          </div>
        </nav>
        <main style={{ padding: '1rem' }}>
         {children}
        </main>
              
         
       

      </body>
    </html>
  );
}
